# Generated by Django 4.0.2 on 2022-02-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='anonym@dipa.ru', max_length=150)),
                ('message', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
